import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs"
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai"

import callmefid from "./assets/avatar1.jpg"
import design from "./assets/design.png"
import code from "./assets/code.png"
import consulting from "./assets/consulting.png"
import web1 from "./assets/web1.png"
import web2 from "./assets/web2.png"
import web3 from "./assets/web3.png"
import { useState } from "react"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  const [toggleButton, setToggleButton] = useState(true)
  return (
    <div className={darkMode ? "dark" : ""}>
      <header>
        <title>Fid Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </header>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-gray-400">
              developedfidd
            </h1>
            <ul className="flex items-center">
              {toggleButton ? (
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => {
                      setDarkMode(!darkMode)
                      setToggleButton(!toggleButton)
                    }}
                    className="cursor-pointer text-2xl dark:text-gray-400"
                  />
                </li>
              ) : (
                <li>
                  <BsFillSunFill
                    onClick={() => {
                      setDarkMode(!darkMode)
                      setToggleButton(!toggleButton)
                    }}
                    className="cursor-pointer text-2xl dark:text-gray-400"
                  />
                </li>
              )}
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#project">
                  Projects
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 dark:text-gray-400">
            <h2 className="text-4xl py-2 text-teal-600 font-medium md:text-6xl">
              Minn Htet Wai
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl ">
              Developer and aspiring learner
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-400">
              Self-taught developer hoping to obtain actual experiences. Join me
              down below and let`s start the tour
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-500">
            <a href="https://twitter.com/MinnHte46482093" target="_blank">
              <AiFillTwitterCircle />
            </a>
            <a
              href="https://www.linkedin.com/in/mc-pro-nunuu-04a211263/"
              target="_blank">
              <AiFillLinkedin />
            </a>
            <a
              href="https://www.youtube.com/channel/UC31Z1JIPdVPrY6WOELOemYQ"
              target="_blank">
              <AiFillYoutube />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <img
              src={callmefid}
              className="contrast-100 saturate-150 brightness-100 hue-rotate-15 absolute top-0 left-0 w-full h-full object-cover"
            />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 mt-6 dark:text-gray-400 dark:font-semibold">
              Services I will offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              I can create design and see probablites for websites. In the
              future, I would like to teach some of the stuff I will learn for
              <span className="text-teal-500"> youtube. </span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Near in the future, I will offer from a wide range of services,
              including brand designs, programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-white ">
              <div>
                <img src={design} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Creative Thinking Abilities
              </h3>
              <p className="py-2">
                Creating layout of website by thinking about the best websites
                I've seen.
              </p>
            </div>
            <div className="text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div>
                <img src={code} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">Careful Manners</h3>
              <p className="py-2">
                As I am super carful person, I pay attention details to a
                website others have missed.
              </p>
            </div>
            <div className="text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <div>
                <img src={consulting} width={100} height={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Well-liked and Well-received
              </h3>
              <p className="py-2">
                As I am likeable person, people tend to stick to me for a
                reason.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 mt-6 dark:text-gray-400 dark:font-semibold">
              Portofolio
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-400">
              Since the beginning of my journey as a freelance developer, I've
              done projects using
              <span className="text-teal-500"> API</span> and
              <span className="text-teal-500"> react</span> Moreover, I worked
              on some projects but not amazing ones but low-leveled noob ones.
            </p>
          </div>
          <div id="project" className="dark:text-gray-400">MY PROJECTS</div>

          <div class="flex flex-col md:flex-row bg-gray-100 rounded-lg shadow-lg overflow-hidden">
            <div class="md:w-1/2">
              <img
                src={web1}
                class="w-full h-full object-cover"
                alt="Project Image"
              />
            </div>
            <div class="md:w-1/2 px-6 py-8 md:p-10 flex flex-col justify-center">
              <h2 class="text-2xl font-semibold mb-2 dark:text-gray-900">
                Youtube Clone Original
              </h2>
              <p class="md:text-lg text-md mb-6 dark:text-gray-900">
                This is the project made by using react and material UI and made
                me understand API more.
              </p>
              <div class="flex flex-col md:flex-row justify-between items-center">
                <div class="md:text-lg text-md mb-4 md:mb-0 dark:text-gray-900">
                  <span class="mr-2">Source Code:</span>
                  <a
                    href="https://github.com/NuNuu4101/youtube-clone"
                    target="_blank">
                    <AiFillGithub class="text-2xl dark:text-gray-900 hover:text-gray-500 transition-colors duration-300" />
                  </a>
                </div>
                <a
                  href="https://youtube-clone-origin.netlify.app/"
                  target="_blank">
                  <button class="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md hover:from-cyan-600 hover:to-teal-600 transition-colors duration-300">
                    Live Demo
                  </button>
                </a>
              </div>
            </div>
          </div>
          <div class="flex flex-col my-8 bg-gray-100 rounded-md shadow-lg overflow-hidden md:flex-row">
            <div class="md:w-1/2">
              <img
                src={web2}
                class="w-full h-full object-cover"
                alt="Project Image"
              />
            </div>
            <div class="md:w-1/2 px-6 py-8 md:p-10 flex flex-col justify-center">
              <h2 class="text-2xl font-semibold mb-2 dark:text-gray-900">
                Youtube Clone API
              </h2>
              <p class="md:text-lg text-md mb-6 dark:text-gray-900">
                This is the project made by using react and material UI and made
                me understand API more.
              </p>
              <div class="flex flex-col md:flex-row justify-between items-center">
                <div class="md:text-lg text-md mb-4 md:mb-0 dark:text-gray-900">
                  <span class="mr-2">Source Code:</span>
                  <a
                    href="https://github.com/NuNuu4101/youtube-clone"
                    target="_blank">
                    <AiFillGithub class="text-2xl dark:text-gray-900 hover:text-gray-500 transition-colors duration-300" />
                  </a>
                </div>
                <a href="https://youtubeclone4101.netlify.app/" target="_blank">
                  <button class="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md hover:from-cyan-600 hover:to-teal-600 transition-colors duration-300">
                    Live Demo
                  </button>
                </a>
              </div>
            </div>
          </div>
          <div class="flex flex-col my-8 bg-gray-100 rounded-md shadow-lg overflow-hidden md:flex-row">
            <div class="md:w-1/2">
              <img
                src={web3}
                class="w-full h-full object-cover"
                alt="Project Image"
              />
            </div>
            <div class="md:w-1/2 px-6 py-8 md:p-10 flex flex-col justify-center">
              <h2 class="text-2xl font-semibold mb-2 dark:text-gray-900">
                Shoes Shopping Website
              </h2>
              <p class="md:text-lg text-md mb-6 dark:text-gray-900">
                This is the project made by using react and tailwind css. This
                is the first project ever to get through blackouts and
                connection issues and depression. However, it still managed to
                get through all of that. Its a very amazing website for me.
              </p>
              <div class="flex flex-col md:flex-row justify-between items-center">
                <div class="md:text-lg text-md mb-4 md:mb-0 dark:text-gray-900">
                  <span class="mr-2">Source Code:</span>
                  <a
                    href="https://github.com/NuNuu4101/my-first-project"
                    target="_blank">
                    <AiFillGithub class="text-2xl dark:text-gray-900 hover:text-gray-500 transition-colors duration-300" />
                  </a>
                </div>
                <a
                  href="https://my-first-shopping-website.netlify.app/"
                  target="_blank">
                  <button class="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md hover:from-cyan-600 hover:to-teal-600 transition-colors duration-300">
                    Live Demo
                  </button>
                </a>
              </div>
            </div>
          </div>
        </section>
        <footer className="dark:bg-gray-900  dark:text-gray-400  border-t text-center">
        Made with love and care by CallMeFidd.
      </footer>
      </main>
     
    </div>
  )
}
